/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIdIndexRouteImport } from './routes/dashboard.$id.index'
import { Route as DashboardIdSquadRouteImport } from './routes/dashboard.$id.squad'
import { Route as DashboardIdPlayerPlayerIdRouteImport } from './routes/dashboard.$id.player.$playerId'
import { Route as DashboardIdMatchMatchKeyRouteImport } from './routes/dashboard.$id.match.$matchKey'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdIndexRoute = DashboardIdIndexRouteImport.update({
  id: '/dashboard/$id/',
  path: '/dashboard/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdSquadRoute = DashboardIdSquadRouteImport.update({
  id: '/dashboard/$id/squad',
  path: '/dashboard/$id/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdPlayerPlayerIdRoute =
  DashboardIdPlayerPlayerIdRouteImport.update({
    id: '/dashboard/$id/player/$playerId',
    path: '/dashboard/$id/player/$playerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardIdMatchMatchKeyRoute =
  DashboardIdMatchMatchKeyRouteImport.update({
    id: '/dashboard/$id/match/$matchKey',
    path: '/dashboard/$id/match/$matchKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/tables': typeof TablesRoute
  '/dashboard/$id/squad': typeof DashboardIdSquadRoute
  '/dashboard/$id/': typeof DashboardIdIndexRoute
  '/dashboard/$id/match/$matchKey': typeof DashboardIdMatchMatchKeyRoute
  '/dashboard/$id/player/$playerId': typeof DashboardIdPlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/tables': typeof TablesRoute
  '/dashboard/$id/squad': typeof DashboardIdSquadRoute
  '/dashboard/$id': typeof DashboardIdIndexRoute
  '/dashboard/$id/match/$matchKey': typeof DashboardIdMatchMatchKeyRoute
  '/dashboard/$id/player/$playerId': typeof DashboardIdPlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/tables': typeof TablesRoute
  '/dashboard/$id/squad': typeof DashboardIdSquadRoute
  '/dashboard/$id/': typeof DashboardIdIndexRoute
  '/dashboard/$id/match/$matchKey': typeof DashboardIdMatchMatchKeyRoute
  '/dashboard/$id/player/$playerId': typeof DashboardIdPlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hall-of-fame'
    | '/tables'
    | '/dashboard/$id/squad'
    | '/dashboard/$id/'
    | '/dashboard/$id/match/$matchKey'
    | '/dashboard/$id/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/hall-of-fame'
    | '/tables'
    | '/dashboard/$id/squad'
    | '/dashboard/$id'
    | '/dashboard/$id/match/$matchKey'
    | '/dashboard/$id/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/hall-of-fame'
    | '/tables'
    | '/dashboard/$id/squad'
    | '/dashboard/$id/'
    | '/dashboard/$id/match/$matchKey'
    | '/dashboard/$id/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HallOfFameRoute: typeof HallOfFameRoute
  TablesRoute: typeof TablesRoute
  DashboardIdSquadRoute: typeof DashboardIdSquadRoute
  DashboardIdIndexRoute: typeof DashboardIdIndexRoute
  DashboardIdMatchMatchKeyRoute: typeof DashboardIdMatchMatchKeyRoute
  DashboardIdPlayerPlayerIdRoute: typeof DashboardIdPlayerPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id/': {
      id: '/dashboard/$id/'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id/'
      preLoaderRoute: typeof DashboardIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id/squad': {
      id: '/dashboard/$id/squad'
      path: '/dashboard/$id/squad'
      fullPath: '/dashboard/$id/squad'
      preLoaderRoute: typeof DashboardIdSquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id/player/$playerId': {
      id: '/dashboard/$id/player/$playerId'
      path: '/dashboard/$id/player/$playerId'
      fullPath: '/dashboard/$id/player/$playerId'
      preLoaderRoute: typeof DashboardIdPlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id/match/$matchKey': {
      id: '/dashboard/$id/match/$matchKey'
      path: '/dashboard/$id/match/$matchKey'
      fullPath: '/dashboard/$id/match/$matchKey'
      preLoaderRoute: typeof DashboardIdMatchMatchKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HallOfFameRoute: HallOfFameRoute,
  TablesRoute: TablesRoute,
  DashboardIdSquadRoute: DashboardIdSquadRoute,
  DashboardIdIndexRoute: DashboardIdIndexRoute,
  DashboardIdMatchMatchKeyRoute: DashboardIdMatchMatchKeyRoute,
  DashboardIdPlayerPlayerIdRoute: DashboardIdPlayerPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
